### PR TITLE
Fix TChem_AerosolChemistry bug

### LINKED ISSUE #72: TChem_AerosolChemistry_* does not solve gases correctly
The solution from the AerosolChemistry versions does not recover the same solution as the AtmosphericChemistry (and CAMP) when attempting to solve the same mechanism.

Edit: it still isn't clear why this is occurring in some cases. Oscar was unable to replicate the issue on his system.

### PR DESCRIPTION
**Pull request by jcurtis2**
Fixes #72 

Using the CB05 mechanism and solving with Gas Solver (TChem_AtmosphericChemistry) and Gas-Aerosol solver (TChem_AerosolChemistry) where the aerosols have no reactions. These (Gas-only, Gas-Aerosol CVODE/Tines/KK and CAMP) should have identical results.

Check list:

- [x] Verify CVODE
- [x] Verify Tines
  - [x] CPU
  - [x] GPU
- [x] Make change globally from real_type_1d_view_type to subview()

### CODE REVIEW

File: src/core/TChem_AerosolChemistry.cpp [hunk 1]
```diff
@@ -105,10 +105,12 @@ namespace TChem
       const real_type density = sv_at_i.Density();
       const real_type_1d_view_type Ys = sv_at_i.MassFractions();
       const ordinal_type n_active_gas_species = kmcd.nSpec - kmcd.nConstSpec;
-      const auto activeYs = real_type_1d_view_type(Ys.data(),
-                              n_active_gas_species );
-      const auto constYs  = real_type_1d_view_type(Ys.data(),
-                            +n_active_gas_species,  kmcd.nSpec );
+//      const auto activeYs = real_type_1d_view_type(Ys.data(),
```
Comment (odiazib) [inline src/core/TChem_AerosolChemistry.cpp:108]: Let's remove this section of commented-out code.

**Review by odiazib — APPROVED** [review]
Thank you for resolving this bug.

File: src/core/TChem_AerosolChemistry.cpp (hunk 1 above)
Comment (jcurtis2) [reply src/core/TChem_AerosolChemistry.cpp]: Removed both instances of commented out code in [cfce1bb](https://github.com/PCLAeroParams/TChem-atm/pull/73/commits/cfce1bb578362877c5a794478d1d16a9ecb658d6)

**Comment by odiazib** [comment]
@jcurtis2 Can we proceed with merging this PR?

**Review by odiazib — APPROVED** [review]
It looks good to me.
